http:
  port: 80
admin:
  port: 9876
  hostname: 0.0.0.0
apiEndpoints:
  userspace:
    host: '*'
    methods: GET
    scopes:
      - 'read'
  adminspace:
    host: '*'
    methods: POST
    scopes:
      - 'write'
serviceEndpoints:
  customers:
    url: 'http://customers:3000/'
  invoices:
    url: 'http://invoices:3000/'
policies:
  - expression
  - jwt
  - jwtScopes
  - proxy
pipelines:
  - name: default
    apiEndpoints:
      - userspace
      - adminspace
    policies:
      - jwt:
        - action:
            checkCredentialExistence: false
            secretOrPublicKeyFile: "/usr/src/config/expressgateway.pem"
            audience: 'https://api.apitest.lan'
      - jwtScopes:
        - action:
      - proxy:
          - action:
              serviceEndpoint: customers
              changeOrigin: true
            condition:
              name: hostMatch
              pattern: 'api.apitest.lan*'
